
swagger: '2.0'
info:
  title: Portolano - Helm chart repository
  version: "0.1"

produces:
  - text/plain

paths:
  /{filename}:
    get:
      summary: Get the charts index.yaml
      parameters:
        - name: filename
          description: "filename to download (Currently on support index.yaml)"
          in: path
          type: string
          required: true
      responses:
        200:
          description: Return index.yaml
          schema:
            type: file
        404:
          description: File does not exists

  /charts/:
    post:
      summary: Upload a chart archive
      consumes:
        - multipart/form-data
      parameters:
        - name: file
          description: "tar or tar.gz chart archive"
          in: formData
          type: file
          required: true
      responses:
        200:
          description: Ok
          schema:
            type: object
            properties:
              url:
                type: string
                description: "Url to download the archived chart"
                readOnly: true

        400:
          description: Missing file


