
swagger: '2.0'
info:
  title: Portolano - Helm chart repository
  version: "0.1"

produces:
  - text/plain

paths:
  /{filename}:
    get:
      summary: Get the charts index.yaml
      parameters:
        - name: filename
          description: "filename to download (Currently on support index.yaml)"
          in: path
          type: string
          required: true
      responses:
        200:
          description: Return index.yaml
          schema:
            type: file
        404:
          description: File does not exists
