version: "2"

services:
  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"

  s3:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: ABCDEFGHIJKLMNOQRSTU
      MINIO_SECRET_KEY: abcdefghiklmnoqrstuvwxyz1234567890abcdef
    command: server /export
    ports:
      - "9000:9000"

  swift:
    image: morrisjobke/docker-swift-onlyone
    ports:
      - "8080:8080"
